<taunt> ::= <sentence> | <noun>!
<sentence> ::= <equestion>!
<equestion> ::= <wh-word> <noun-p> <past-verb-p> <adv> <noun-s-p2> | <wh-word-complex> <noun-s>
<wh-word> ::= где | что | чьи
<wh-word-complex> ::= при чем тут | кто такой
<noun> ::= <noun-p> | <noun-s>
<noun-p> ::= кабанчики | зяблики | котики | щеночки
<noun-s-p2> ::= лет | помидоров | котиков | щеночков | кабанчиков
<noun-s> ::= ковид | котик | зяблик | пёсик | долдон
<adv> ::= столько
<past-verb-p> ::= были | ели | спали | кодили
